### ISSUE TITLE
Checklist tugas

### ISSUE THREAD

**Issue by chez14** [chez14/tugas-mibd#2]
## Pemimpin
- [x] Insert, update, dan delete karyawan dan klien
- [x] Menutup sebuah kasus
- [x] Meng-assign seorang karyawan tambahan ke suatu kasus
- Melihat statistik-statistik seperti:
  - [ ] Waktu pemrosesan rata-rata tiap kasus
  - [ ] Karyawan yang sedang tidak menangani satupun kasus

## Karyawan
- [x] Mengambil satu buah kasus untuk ditangani
- [x] Mengirim pesan ke kasus tersebut
- [x] Melihat seluruh komunikasi yang ada pada kasus tersebut

## Klien
- [x] Membuka sebuah kasus
- [x] Menutup sebuah kasus
- [x] Mengirim pesan ke kasus tersebut
- [x] Melihat semua pesan yang telah dikirim oleh klien dan karyawan-karyawan ke kasus tersebut
